Repository GameLab-UNIL-EPFL/Lausanne-1830, pull requests merged in 2022-06, with the labels that each got.

#170 Tuto Rework
  db/characters/infoCharacters.xml
  db/characters/notebookCharacterList.xml
  db/dialogues/xml/Dialogues.xml
  db/dialogues/xml/QuestNPC.xml
  scenes/Brasserie/Brasserie.tscn
  scenes/Intro/Intro.tscn
  src/Context.cs
  src/NPC.cs
  src/Notebook.cs
  src/NotebookController.cs
  src/Player.cs
  src/QuestController.cs
  src/shaders/BrewGame.gdshader
Labels: enhancement, Dialogue, Priority

#181 Random UI and other fixes
  .import/Tab.png-856e0f064e155ecf8b42581a4847f2ee.md5
  .import/Tab.png-856e0f064e155ecf8b42581a4847f2ee.stex
  assets/02_architecture/05_moulin/01_int/background.png
  assets/02_architecture/05_moulin/01_int/background.png.import
  assets/02_architecture/05_moulin/01_int/fullScene.aseprite
  assets/06_UI_menus/button.png
  assets/06_UI_menus/button.png.import
  scenes/Brasserie/Brasserie.tscn
  scenes/Brasserie/DeskAnim.tres
  scenes/Flon/Moulin.tscn
  scenes/Interaction/NumberButton.tscn
  scenes/Intro/Intro.tscn
  scenes/Notebook/NotebookList.tscn
  src/Context.cs
  src/Notebook.cs
  src/NotebookList.cs
  src/NumberButton.cs
Labels: Design, UI/UX

#185 More changes and fixes
  .import/shift.png-c944383bfee71b86227254f4e0c0f836.md5
  .import/shift.png-c944383bfee71b86227254f4e0c0f836.stex
  .import/wasd.png-27cbc27c1ba623feb53d9f3990c2e2c3.md5
  .import/wasd.png-27cbc27c1ba623feb53d9f3990c2e2c3.stex
  assets/06_UI_menus/button.aseprite
  assets/06_UI_menus/shift.png
  assets/06_UI_menus/shift.png.import
  assets/06_UI_menus/wasd.png
  assets/06_UI_menus/wasd.png.import
  assets/wasd.aseprite
  db/characters/infoCharacters.xml
  db/characters/notebookCharacterList.xml
  db/dialogues/xml/Dialogues.xml
  scenes/Brasserie/Brasserie.tscn
  scenes/Casino/Casino.tscn
  scenes/Flon/Flon.tscn
  scenes/Flon/Moulin.tscn
  scenes/Interaction/TextBox.tscn
  scenes/Intro/Intro.tscn
  scenes/Palud/ProtoPalud.tscn
  scenes/Player.tscn
  src/Context.cs
  src/Intro.cs
  src/Notebook.cs
  src/TextBox.cs
Labels: Design, Dialogue

#187 Final issues fixed
  scenes/Casino/Casino.tscn
  scenes/Intro/Intro.tscn
  scenes/Notebook/Notebook.tscn
  scenes/Palud/ProtoPalud.tscn
  src/NPC.cs
  src/Notebook.cs
  src/NumberButton.cs
  src/Player.cs
Labels: bug

#206 Elisabeth CharInfo overriding objective bug
  src/Notebook.cs
Labels: bug
