Repository GameLab-UNIL-EPFL/Lausanne-1830, pull requests merged in 2022-03, with the labels that each got.

#78 Notebook Tabs
  db/characters/notebookCharacterList.xml
  project.godot
  scenes/Casino/Casino.tscn
  scenes/Context.tscn
  scenes/Flon/Flon.tscn
  scenes/Notebook/Notebook.tscn
  src/Context.cs
  src/NPC.cs
  src/Notebook.cs
  src/Player.cs
  src/QuestController.cs
Labels: Gameplay

#91 Small fixes
  scenes/Brasserie/Brasserie.tscn
  scenes/Notebook/Map.tscn
  scenes/Notebook/MapIcon.tscn
  scenes/Palud/ProtoPalud.tscn
  src/MapIcon.cs
Labels: Design

#95 Map add-ons and other various Quality of Life improvements
  scenes/Brasserie/Brasserie.tscn
  scenes/Casino/Casino.tscn
  scenes/Flon/Flon.tscn
  scenes/Notebook/Map.tscn
  scenes/Notebook/Notebook.tscn
  scenes/Palud/Fountain.tscn
  scenes/Palud/ProtoPalud.tscn
  src/Context.cs
  src/Item.cs
  src/Map.cs
  src/MapIcon.cs
  src/NPC.cs
  src/Notebook.cs
  src/NotebookController.cs
  src/Player.cs
Labels: enhancement

#112 Design fix
  .import/Space.png-477d75cbbf29abd7b80a41528b9db472.md5
  .import/Space.png-477d75cbbf29abd7b80a41528b9db472.stex
  .import/Tab.png-856e0f064e155ecf8b42581a4847f2ee.md5
  .import/Tab.png-856e0f064e155ecf8b42581a4847f2ee.stex
  assets/06_UI_menus/Space.png
  assets/06_UI_menus/Space.png.import
  assets/06_UI_menus/Tab.png
  assets/06_UI_menus/Tab.png.import
  db/characters/notebookCharacterList.xml
  db/dialogues/xml/Dialogues.xml
  project.godot
  scenes/Brasserie/Brasserie.tscn
  scenes/Casino/Casino.tscn
  scenes/Flon/Flon.tscn
  scenes/Interaction/PressSpace.tscn
  scenes/Interaction/PressTab.tscn
  scenes/Interaction/TextBox.tscn
  scenes/NPC.tscn
  scenes/Notebook/Notebook.tscn
  scenes/Palud/ProtoPalud.tscn
  src/NPC.cs
  src/Notebook.cs
  src/TextBox.cs
Labels: Design, Dialogue

#121 New Casino BG
  assets/02_architecture/04_casino/background.png
  assets/02_architecture/04_casino/casino.aseprite
  assets/02_architecture/04_casino/casino.png
  assets/02_architecture/04_casino/fullScene.aseprite
Labels: Art, Design
